#--- STREAMLIT THEME CONFIGURATION ---
# This file defines the color theme for the Streamlit app.
# To use this, create a folder named ".streamlit" in your project's root directory
# and save this file as "config.toml" inside it.

[theme]
#--- UMKC COLORS ---
# Main (UMKC Blue) - Used for sidebar background
#"41B6E6"

# Secondary (UMKC Gold) - Used for interactive elements
primaryColor = "#EAAA00"

# Alternate (Alternate Blue) - Can be used if needed, but primaryColor is the main accent
backgroundColor = "#407EC9"

# Light - Used for the main app background
secondaryBackgroundColor = "#EAAA00"

# Dark - Used for text
textColor = "#000000"